---

- name: Install Shorewall
  apt:
    name: shorewall
    state: present
  tags: shorewall
  register: result
  until: result is succeeded

- name: /etc/default/shorewall
  template:
    dest: /etc/default/shorewall
    src: default/shorewall.j2
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall
  tags: shorewall

- name: Shorewall configuration files
  template:
    dest: "/etc/shorewall/{{ item }}"
    src: "shorewall/{{ item }}.j2"
    owner: root
    group: root
    mode: 0640
  with_items:
    - interfaces
    - zones
    - policy
    - rules
    - snat
  notify: restart shorewall
  tags: shorewall

- name: Shorewall main config
  template:
    dest: "/etc/shorewall/shorewall.conf"
    src: "shorewall/shorewall.conf.j2"
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall
  tags: shorewall

- name: Start and enable the Shorewall service
  async: 30
  poll: 5
  service:
    name: shorewall
    state: started
    enabled: yes
  tags: shorewall
