---

- name: Install Shorewall6
  apt:
    name: shorewall6
  tags: [ 'shorewall', 'shorewall6' ]
  register: result
  until: result is succeeded

- name: /etc/default/shorewall6
  template:
    dest: /etc/default/shorewall6
    src: default/shorewall6.j2
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall6
  tags: [ 'shorewall', 'shorewall6' ]

- name: Shorewall6 configuration files
  template:
    dest: "/etc/shorewall6/{{ item }}"
    src: "shorewall6/{{ item }}.j2"
    owner: root
    group: root
    mode: 0640
  with_items:
    - interfaces
    - zones
    - policy
    - rules
    - snat
  notify: restart shorewall6
  tags: [ 'shorewall', 'shorewall6' ]

- name: Start and enable the Shorewall6 service
  async: 30
  poll: 5
  service:
    name: shorewall
    state: started
    enabled: yes
  tags: [ 'shorewall', 'shorewall6' ]
